// Generated by CIRCT firtool-1.62.1
module EthernetPCSRXFSM(
  input        clock,
               reset,
               io_config,
               io_pcs_reset,
  output       io_rx_symb_vector_ready,
  input        io_rx_symb_vector_valid,
  input  [2:0] io_rx_symb_vector_bits_0,
               io_rx_symb_vector_bits_1,
               io_rx_symb_vector_bits_2,
               io_rx_symb_vector_bits_3,
  input  [7:0] io_from_decoder_symbols,
  output       io_receive1000BT,
               io_rxerror_status,
  output [7:0] io_rxd,
  output       io_rx_dv,
               io_rx_er
);

  reg  [3:0] state;
  reg  [2:0] rx_symb_vector_prev_0;
  reg  [2:0] rx_symb_vector_prev_1;
  reg  [2:0] rx_symb_vector_prev_2;
  reg  [2:0] rx_symb_vector_prev_3;
  wire       _GEN = state == 4'h0;
  wire       _GEN_0 = state == 4'h1;
  wire       _GEN_1 = state == 4'h4;
  wire       _GEN_2 = state == 4'h2;
  wire       _GEN_3 = state == 4'h3;
  wire       _GEN_4 = state == 4'h5;
  wire       _GEN_5 = state == 4'h6;
  wire       _GEN_6 = state == 4'h7;
  wire       _GEN_7 = state == 4'h8;
  wire       _GEN_8 = _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6;
  wire       _GEN_9 = _GEN | _GEN_0;
  always @(posedge clock) begin
    if (reset)
      state <= 4'h0;
    else begin
      automatic logic             _GEN_10 = io_rx_symb_vector_bits_0 == 3'h0;
      automatic logic             _GEN_11 = io_rx_symb_vector_bits_1 == 3'h0;
      automatic logic             _GEN_12 = io_rx_symb_vector_bits_2 == 3'h0;
      automatic logic             _GEN_13 = io_rx_symb_vector_bits_3 == 3'h0;
      automatic logic             _GEN_14 = _GEN_10 & _GEN_11;
      automatic logic             _GEN_15 = _GEN_14 & _GEN_12;
      automatic logic             _GEN_16 = io_rx_symb_vector_bits_0 == 3'h6;
      automatic logic             _GEN_17 = _GEN_16 & _GEN_11;
      automatic logic             _GEN_18 = _GEN_17 & _GEN_12;
      automatic logic             _GEN_19 = io_rx_symb_vector_bits_1 == 3'h6;
      automatic logic             _GEN_20 = _GEN_10 & _GEN_19;
      automatic logic             _GEN_21 = _GEN_20 & _GEN_12;
      automatic logic             _GEN_22 = _GEN_16 & _GEN_19;
      automatic logic             _GEN_23 = _GEN_22 & _GEN_12;
      automatic logic             _GEN_24 = io_rx_symb_vector_bits_2 == 3'h6;
      automatic logic             _GEN_25 = _GEN_14 & _GEN_24;
      automatic logic             _GEN_26 = _GEN_17 & _GEN_24;
      automatic logic             _GEN_27 = _GEN_20 & _GEN_24;
      automatic logic             _GEN_28 = _GEN_22 & _GEN_24;
      automatic logic             _GEN_29 = io_rx_symb_vector_bits_3 == 3'h6;
      automatic logic             _GEN_30 =
        _GEN_15 & _GEN_13 | _GEN_18 & _GEN_13 | _GEN_21 & _GEN_13 | _GEN_23 & _GEN_13
        | _GEN_25 & _GEN_13 | _GEN_26 & _GEN_13 | _GEN_27 & _GEN_13 | _GEN_28 & _GEN_13
        | _GEN_15 & _GEN_29 | _GEN_18 & _GEN_29 | _GEN_21 & _GEN_29 | _GEN_23 & _GEN_29
        | _GEN_25 & _GEN_29 | _GEN_26 & _GEN_29 | _GEN_27 & _GEN_29 | _GEN_28 & _GEN_29;
      automatic logic             _GEN_31 = rx_symb_vector_prev_0 == 3'h2;
      automatic logic             _GEN_32 = rx_symb_vector_prev_1 == 3'h2;
      automatic logic             _GEN_33 = rx_symb_vector_prev_2 == 3'h2;
      automatic logic             _GEN_34 = rx_symb_vector_prev_3 == 3'h2;
      automatic logic             _GEN_35 = _GEN_31 & _GEN_32;
      automatic logic             _GEN_36 = _GEN_35 & _GEN_33 & _GEN_34;
      automatic logic             _GEN_37 = io_rx_symb_vector_bits_0 == 3'h2;
      automatic logic             _GEN_38 = io_rx_symb_vector_bits_1 == 3'h2;
      automatic logic             _GEN_39 = io_rx_symb_vector_bits_2 == 3'h2;
      automatic logic             _GEN_40 = _GEN_37 & _GEN_38;
      automatic logic             _GEN_41 = _GEN_40 & _GEN_39 & _GEN_29;
      automatic logic             _GEN_42 = io_rx_symb_vector_valid & _GEN_30;
      automatic logic             _GEN_43 = rx_symb_vector_prev_0 == 3'h0;
      automatic logic             _GEN_44 = rx_symb_vector_prev_1 == 3'h0;
      automatic logic             _GEN_45 = rx_symb_vector_prev_2 == 3'h0;
      automatic logic             _GEN_46 = rx_symb_vector_prev_3 == 3'h0;
      automatic logic             _GEN_47 = _GEN_43 & _GEN_44;
      automatic logic             _GEN_48 = _GEN_47 & _GEN_45;
      automatic logic             _GEN_49 = rx_symb_vector_prev_2 == 3'h1;
      automatic logic             _GEN_50 = rx_symb_vector_prev_3 == 3'h1;
      automatic logic             _GEN_51 = _GEN_47 & _GEN_49;
      automatic logic             _GEN_52 = rx_symb_vector_prev_1 == 3'h1;
      automatic logic             _GEN_53 = _GEN_43 & _GEN_52;
      automatic logic             _GEN_54 = _GEN_53 & _GEN_49;
      automatic logic             _GEN_55 = _GEN_53 & _GEN_45;
      automatic logic             _GEN_56 = rx_symb_vector_prev_0 == 3'h6;
      automatic logic             _GEN_57 = _GEN_56 & _GEN_44;
      automatic logic             _GEN_58 = _GEN_57 & _GEN_45;
      automatic logic             _GEN_59 = _GEN_57 & _GEN_49;
      automatic logic             _GEN_60 = _GEN_56 & _GEN_52;
      automatic logic             _GEN_61 = _GEN_60 & _GEN_49;
      automatic logic             _GEN_62 = _GEN_60 & _GEN_45;
      automatic logic             _GEN_63 = rx_symb_vector_prev_1 == 3'h6;
      automatic logic             _GEN_64 = _GEN_43 & _GEN_63;
      automatic logic             _GEN_65 = _GEN_64 & _GEN_45;
      automatic logic             _GEN_66 = _GEN_64 & _GEN_49;
      automatic logic             _GEN_67 = _GEN_43 & (&rx_symb_vector_prev_1);
      automatic logic             _GEN_68 = _GEN_67 & _GEN_49;
      automatic logic             _GEN_69 = _GEN_67 & _GEN_45;
      automatic logic             _GEN_70 = _GEN_56 & _GEN_32;
      automatic logic             _GEN_71 = _GEN_70 & _GEN_45;
      automatic logic             _GEN_72 = _GEN_56 & _GEN_63;
      automatic logic             _GEN_73 = _GEN_72 & _GEN_49;
      automatic logic             _GEN_74 = _GEN_56 & (&rx_symb_vector_prev_1);
      automatic logic             _GEN_75 = _GEN_74 & _GEN_49;
      automatic logic             _GEN_76 = _GEN_74 & _GEN_45;
      automatic logic             _GEN_77 = rx_symb_vector_prev_2 == 3'h6;
      automatic logic             _GEN_78 = _GEN_47 & _GEN_77;
      automatic logic             _GEN_79 = _GEN_47 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_80 = _GEN_53 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_81 = _GEN_53 & _GEN_77;
      automatic logic             _GEN_82 = _GEN_57 & _GEN_77;
      automatic logic             _GEN_83 = _GEN_57 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_84 = _GEN_60 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_85 = _GEN_60 & _GEN_77;
      automatic logic             _GEN_86 = _GEN_64 & _GEN_77;
      automatic logic             _GEN_87 = _GEN_64 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_88 = _GEN_67 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_89 = _GEN_67 & _GEN_77;
      automatic logic             _GEN_90 = _GEN_72 & _GEN_77;
      automatic logic             _GEN_91 = _GEN_72 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_92 = _GEN_74 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_93 = _GEN_74 & _GEN_77;
      automatic logic             _GEN_94 = rx_symb_vector_prev_3 == 3'h6;
      automatic logic             _GEN_95 = _GEN_72 & _GEN_45;
      automatic logic             _GEN_96 = rx_symb_vector_prev_0 == 3'h1;
      automatic logic             _GEN_97 = _GEN_96 & _GEN_52;
      automatic logic             _GEN_98 = _GEN_97 & _GEN_49;
      automatic logic             _GEN_99 = _GEN_97 & _GEN_45;
      automatic logic             _GEN_100 = _GEN_96 & _GEN_44;
      automatic logic             _GEN_101 = _GEN_100 & _GEN_45;
      automatic logic             _GEN_102 = _GEN_100 & _GEN_49;
      automatic logic             _GEN_103 = (&rx_symb_vector_prev_0) & _GEN_52;
      automatic logic             _GEN_104 = _GEN_103 & _GEN_49;
      automatic logic             _GEN_105 = _GEN_103 & _GEN_45;
      automatic logic             _GEN_106 = (&rx_symb_vector_prev_0) & _GEN_44;
      automatic logic             _GEN_107 = _GEN_106 & _GEN_45;
      automatic logic             _GEN_108 = _GEN_106 & _GEN_49;
      automatic logic             _GEN_109 = _GEN_96 & (&rx_symb_vector_prev_1);
      automatic logic             _GEN_110 = _GEN_109 & _GEN_49;
      automatic logic             _GEN_111 = _GEN_109 & _GEN_45;
      automatic logic             _GEN_112 = _GEN_96 & _GEN_63;
      automatic logic             _GEN_113 = _GEN_112 & _GEN_45;
      automatic logic             _GEN_114 = _GEN_112 & _GEN_49;
      automatic logic             _GEN_115 =
        (&rx_symb_vector_prev_0) & (&rx_symb_vector_prev_1);
      automatic logic             _GEN_116 = _GEN_115 & _GEN_49;
      automatic logic             _GEN_117 = _GEN_115 & _GEN_45;
      automatic logic             _GEN_118 = (&rx_symb_vector_prev_0) & _GEN_63;
      automatic logic             _GEN_119 = _GEN_118 & _GEN_45;
      automatic logic             _GEN_120 = _GEN_118 & _GEN_49;
      automatic logic             _GEN_121 = _GEN_97 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_122 = _GEN_97 & _GEN_77;
      automatic logic             _GEN_123 = _GEN_100 & _GEN_77;
      automatic logic             _GEN_124 = _GEN_100 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_125 = _GEN_103 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_126 = _GEN_103 & _GEN_77;
      automatic logic             _GEN_127 = _GEN_106 & _GEN_77;
      automatic logic             _GEN_128 = _GEN_106 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_129 = _GEN_109 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_130 = _GEN_109 & _GEN_77;
      automatic logic             _GEN_131 = _GEN_112 & _GEN_77;
      automatic logic             _GEN_132 = _GEN_112 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_133 = _GEN_115 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_134 = _GEN_115 & _GEN_77;
      automatic logic             _GEN_135 = _GEN_118 & _GEN_77;
      automatic logic             _GEN_136 = _GEN_118 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_137 = _GEN_31 & _GEN_44;
      automatic logic             _GEN_138 = _GEN_137 & _GEN_45;
      automatic logic             _GEN_139 = _GEN_137 & _GEN_49;
      automatic logic             _GEN_140 = _GEN_31 & _GEN_52;
      automatic logic             _GEN_141 = _GEN_140 & _GEN_49;
      automatic logic             _GEN_142 = _GEN_140 & _GEN_45;
      automatic logic             _GEN_143 = _GEN_31 & _GEN_63;
      automatic logic             _GEN_144 = _GEN_143 & _GEN_45;
      automatic logic             _GEN_145 = _GEN_143 & _GEN_49;
      automatic logic             _GEN_146 = _GEN_31 & (&rx_symb_vector_prev_1);
      automatic logic             _GEN_147 = _GEN_146 & _GEN_49;
      automatic logic             _GEN_148 = _GEN_146 & _GEN_45;
      automatic logic             _GEN_149 = _GEN_137 & _GEN_77;
      automatic logic             _GEN_150 = _GEN_137 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_151 = _GEN_140 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_152 = _GEN_140 & _GEN_77;
      automatic logic             _GEN_153 = _GEN_143 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_154 = _GEN_146 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_155 = _GEN_146 & _GEN_77;
      automatic logic             _GEN_156 = _GEN_143 & _GEN_77;
      automatic logic             _GEN_157 = _GEN_47 & _GEN_33;
      automatic logic             _GEN_158 = _GEN_97 & _GEN_33;
      automatic logic             _GEN_159 = _GEN_100 & _GEN_33;
      automatic logic             _GEN_160 = _GEN_53 & _GEN_33;
      automatic logic             _GEN_161 = _GEN_57 & _GEN_33;
      automatic logic             _GEN_162 = _GEN_103 & _GEN_33;
      automatic logic             _GEN_163 = _GEN_106 & _GEN_33;
      automatic logic             _GEN_164 = _GEN_60 & _GEN_33;
      automatic logic             _GEN_165 = _GEN_64 & _GEN_33;
      automatic logic             _GEN_166 = _GEN_109 & _GEN_33;
      automatic logic             _GEN_167 = _GEN_112 & _GEN_33;
      automatic logic             _GEN_168 = _GEN_67 & _GEN_33;
      automatic logic             _GEN_169 = _GEN_72 & _GEN_33;
      automatic logic             _GEN_170 = _GEN_115 & _GEN_33;
      automatic logic             _GEN_171 = _GEN_118 & _GEN_33;
      automatic logic             _GEN_172 = _GEN_74 & _GEN_33;
      automatic logic             _GEN_173 = _GEN_43 & _GEN_32;
      automatic logic             _GEN_174 = _GEN_173 & _GEN_45;
      automatic logic             _GEN_175 = _GEN_173 & _GEN_49;
      automatic logic             _GEN_176 = _GEN_96 & _GEN_32;
      automatic logic             _GEN_177 = _GEN_176 & _GEN_45;
      automatic logic             _GEN_178 = _GEN_176 & _GEN_49;
      automatic logic             _GEN_179 = _GEN_70 & _GEN_49;
      automatic logic             _GEN_180 = (&rx_symb_vector_prev_0) & _GEN_32;
      automatic logic             _GEN_181 = _GEN_180 & _GEN_45;
      automatic logic             _GEN_182 = _GEN_180 & _GEN_49;
      automatic logic             _GEN_183 = _GEN_173 & _GEN_77;
      automatic logic             _GEN_184 = _GEN_173 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_185 = _GEN_176 & _GEN_77;
      automatic logic             _GEN_186 = _GEN_176 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_187 = _GEN_70 & _GEN_77;
      automatic logic             _GEN_188 = _GEN_70 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_189 = _GEN_180 & _GEN_77;
      automatic logic             _GEN_190 = _GEN_180 & (&rx_symb_vector_prev_2);
      automatic logic             _GEN_191 = io_rx_symb_vector_bits_3 == 3'h2;
      automatic logic             _GEN_192 = (&io_rx_symb_vector_bits_0) & _GEN_38;
      automatic logic             _GEN_193 = io_rx_symb_vector_bits_1 == 3'h1;
      automatic logic             _GEN_194 = _GEN_37 & _GEN_193;
      automatic logic [15:0][3:0] _GEN_195 =
        {{state},
         {state},
         {state},
         {state},
         {io_rx_symb_vector_valid ? 4'h0 : 4'hB},
         {{3'h5, io_rx_symb_vector_valid}},
         {io_rx_symb_vector_valid ? 4'hA : 4'h9},
         {io_rx_symb_vector_valid ? 4'h5 : 4'h8},
         {{2'h1, ~io_rx_symb_vector_valid, 1'h1}},
         {_GEN_42 ? 4'h0 : 4'h6},
         {io_rx_symb_vector_valid
          & (_GEN_48 & _GEN_46 | _GEN_51 & _GEN_50 | _GEN_54 & _GEN_46 | _GEN_55 & _GEN_50
             | _GEN_58 & _GEN_46 | _GEN_59 & _GEN_50 | _GEN_61 & _GEN_46 | _GEN_62
             & _GEN_50 | _GEN_65 & _GEN_46 | _GEN_66 & _GEN_50 | _GEN_68 & _GEN_46
             | _GEN_69 & _GEN_50 | _GEN_71 & _GEN_46 | _GEN_73 & _GEN_50 | _GEN_75
             & _GEN_46 | _GEN_76 & _GEN_50 | _GEN_78 & _GEN_46 | _GEN_79 & _GEN_50
             | _GEN_80 & _GEN_46 | _GEN_81 & _GEN_50 | _GEN_82 & _GEN_46 | _GEN_83
             & _GEN_50 | _GEN_84 & _GEN_46 | _GEN_85 & _GEN_50 | _GEN_86 & _GEN_46
             | _GEN_87 & _GEN_50 | _GEN_88 & _GEN_46 | _GEN_89 & _GEN_50 | _GEN_90
             & _GEN_46 | _GEN_91 & _GEN_50 | _GEN_92 & _GEN_46 | _GEN_93 & _GEN_50
             | _GEN_48 & _GEN_94 | _GEN_51 & (&rx_symb_vector_prev_3) | _GEN_54 & _GEN_94
             | _GEN_55 & (&rx_symb_vector_prev_3) | _GEN_58 & _GEN_94 | _GEN_59
             & (&rx_symb_vector_prev_3) | _GEN_61 & _GEN_94 | _GEN_62 & _GEN_94 | _GEN_65
             & _GEN_94 | _GEN_66 & (&rx_symb_vector_prev_3) | _GEN_68 & _GEN_94 | _GEN_69
             & (&rx_symb_vector_prev_3) | _GEN_95 & _GEN_94 | _GEN_73
             & (&rx_symb_vector_prev_3) | _GEN_75 & _GEN_94 | _GEN_76
             & (&rx_symb_vector_prev_3) | _GEN_78 & _GEN_94 | _GEN_79
             & (&rx_symb_vector_prev_3) | _GEN_80 & _GEN_94 | _GEN_81
             & (&rx_symb_vector_prev_3) | _GEN_82 & _GEN_94 | _GEN_83
             & (&rx_symb_vector_prev_3) | _GEN_84 & _GEN_94 | _GEN_85
             & (&rx_symb_vector_prev_3) | _GEN_86 & _GEN_94 | _GEN_87
             & (&rx_symb_vector_prev_3) | _GEN_88 & _GEN_94 | _GEN_89
             & (&rx_symb_vector_prev_3) | _GEN_90 & _GEN_94 | _GEN_91
             & (&rx_symb_vector_prev_3) | _GEN_92 & _GEN_94 | _GEN_93
             & (&rx_symb_vector_prev_3) | _GEN_98 & _GEN_50 | _GEN_99 & _GEN_46 | _GEN_101
             & _GEN_50 | _GEN_102 & _GEN_46 | _GEN_104 & _GEN_50 | _GEN_105 & _GEN_46
             | _GEN_107 & _GEN_50 | _GEN_108 & _GEN_46 | _GEN_110 & _GEN_50 | _GEN_111
             & _GEN_46 | _GEN_113 & _GEN_50 | _GEN_114 & _GEN_46 | _GEN_116 & _GEN_50
             | _GEN_117 & _GEN_46 | _GEN_119 & _GEN_50 | _GEN_120 & _GEN_46 | _GEN_121
             & _GEN_50 | _GEN_122 & _GEN_46 | _GEN_123 & _GEN_50 | _GEN_124 & _GEN_46
             | _GEN_125 & _GEN_50 | _GEN_126 & _GEN_46 | _GEN_127 & _GEN_50 | _GEN_128
             & _GEN_46 | _GEN_129 & _GEN_50 | _GEN_130 & _GEN_46 | _GEN_131 & _GEN_50
             | _GEN_132 & _GEN_46 | _GEN_133 & _GEN_50 | _GEN_134 & _GEN_46 | _GEN_135
             & _GEN_50 | _GEN_136 & _GEN_46 | _GEN_98 & (&rx_symb_vector_prev_3) | _GEN_99
             & _GEN_94 | _GEN_101 & (&rx_symb_vector_prev_3) | _GEN_102 & _GEN_94
             | _GEN_104 & (&rx_symb_vector_prev_3) | _GEN_105 & _GEN_94 | _GEN_107
             & (&rx_symb_vector_prev_3) | _GEN_108 & _GEN_94 | _GEN_110
             & (&rx_symb_vector_prev_3) | _GEN_111 & _GEN_94 | _GEN_113
             & (&rx_symb_vector_prev_3) | _GEN_114 & _GEN_94 | _GEN_116
             & (&rx_symb_vector_prev_3) | _GEN_117 & _GEN_94 | _GEN_119
             & (&rx_symb_vector_prev_3) | _GEN_120 & _GEN_94 | _GEN_121
             & (&rx_symb_vector_prev_3) | _GEN_122 & _GEN_94 | _GEN_123
             & (&rx_symb_vector_prev_3) | _GEN_124 & _GEN_94 | _GEN_125
             & (&rx_symb_vector_prev_3) | _GEN_126 & _GEN_94 | _GEN_127
             & (&rx_symb_vector_prev_3) | _GEN_128 & _GEN_94 | _GEN_129
             & (&rx_symb_vector_prev_3) | _GEN_130 & _GEN_94 | _GEN_131
             & (&rx_symb_vector_prev_3) | _GEN_132 & _GEN_94 | _GEN_133
             & (&rx_symb_vector_prev_3) | _GEN_134 & _GEN_94 | _GEN_135
             & (&rx_symb_vector_prev_3) | _GEN_136 & _GEN_94 | _GEN_138 & _GEN_46
             | _GEN_139 & _GEN_50 | _GEN_141 & _GEN_46 | _GEN_142 & _GEN_50 | _GEN_144
             & _GEN_46 | _GEN_145 & _GEN_50 | _GEN_147 & _GEN_46 | _GEN_148 & _GEN_50
             | _GEN_149 & _GEN_46 | _GEN_150 & _GEN_50 | _GEN_151 & _GEN_46 | _GEN_152
             & _GEN_50 | _GEN_153 & _GEN_50 | _GEN_154 & _GEN_46 | _GEN_155 & _GEN_50
             | _GEN_138 & _GEN_94 | _GEN_139 & (&rx_symb_vector_prev_3) | _GEN_141
             & _GEN_94 | _GEN_142 & (&rx_symb_vector_prev_3) | _GEN_144 & _GEN_94
             | _GEN_145 & (&rx_symb_vector_prev_3) | _GEN_147 & _GEN_94 | _GEN_148
             & (&rx_symb_vector_prev_3) | _GEN_149 & _GEN_94 | _GEN_150
             & (&rx_symb_vector_prev_3) | _GEN_151 & _GEN_94 | _GEN_152
             & (&rx_symb_vector_prev_3) | _GEN_156 & _GEN_94 | _GEN_153
             & (&rx_symb_vector_prev_3) | _GEN_154 & _GEN_94 | _GEN_155
             & (&rx_symb_vector_prev_3) | _GEN_157 & _GEN_46 | _GEN_158 & _GEN_46
             | _GEN_159 & _GEN_50 | _GEN_160 & _GEN_50 | _GEN_161 & _GEN_46 | _GEN_162
             & _GEN_46 | _GEN_163 & _GEN_50 | _GEN_164 & _GEN_50 | _GEN_165 & _GEN_46
             | _GEN_166 & _GEN_46 | _GEN_167 & _GEN_50 | _GEN_168 & _GEN_50 | _GEN_169
             & _GEN_46 | _GEN_170 & _GEN_46 | _GEN_171 & _GEN_50 | _GEN_172 & _GEN_50
             | _GEN_157 & _GEN_94 | _GEN_158 & _GEN_94 | _GEN_159
             & (&rx_symb_vector_prev_3) | _GEN_160 & (&rx_symb_vector_prev_3) | _GEN_161
             & _GEN_94 | _GEN_162 & _GEN_94 | _GEN_163 & (&rx_symb_vector_prev_3)
             | _GEN_164 & (&rx_symb_vector_prev_3) | _GEN_165 & _GEN_94 | _GEN_166
             & _GEN_94 | _GEN_167 & (&rx_symb_vector_prev_3) | _GEN_168
             & (&rx_symb_vector_prev_3) | _GEN_169 & _GEN_94 | _GEN_170 & _GEN_94
             | _GEN_171 & (&rx_symb_vector_prev_3) | _GEN_172 & (&rx_symb_vector_prev_3)
             | _GEN_174 & _GEN_46 | _GEN_175 & _GEN_50 | _GEN_177 & _GEN_50 | _GEN_178
             & _GEN_46 | _GEN_179 & _GEN_50 | _GEN_181 & _GEN_50 | _GEN_182 & _GEN_46
             | _GEN_183 & _GEN_46 | _GEN_184 & _GEN_50 | _GEN_185 & _GEN_50 | _GEN_186
             & _GEN_46 | _GEN_187 & _GEN_46 | _GEN_188 & _GEN_50 | _GEN_189 & _GEN_50
             | _GEN_190 & _GEN_46 | _GEN_174 & _GEN_94 | _GEN_175
             & (&rx_symb_vector_prev_3) | _GEN_177 & (&rx_symb_vector_prev_3) | _GEN_178
             & _GEN_94 | _GEN_71 & _GEN_94 | _GEN_179 & (&rx_symb_vector_prev_3)
             | _GEN_181 & (&rx_symb_vector_prev_3) | _GEN_182 & _GEN_94 | _GEN_183
             & _GEN_94 | _GEN_184 & (&rx_symb_vector_prev_3) | _GEN_185
             & (&rx_symb_vector_prev_3) | _GEN_186 & _GEN_94 | _GEN_187 & _GEN_94
             | _GEN_188 & (&rx_symb_vector_prev_3) | _GEN_189 & (&rx_symb_vector_prev_3)
             | _GEN_190 & _GEN_94 | _GEN_48 & _GEN_34 | _GEN_99 & _GEN_34 | _GEN_54
             & _GEN_34 | _GEN_102 & _GEN_34 | _GEN_58 & _GEN_34 | _GEN_105 & _GEN_34
             | _GEN_61 & _GEN_34 | _GEN_108 & _GEN_34 | _GEN_65 & _GEN_34 | _GEN_111
             & _GEN_34 | _GEN_68 & _GEN_34 | _GEN_114 & _GEN_34 | _GEN_95 & _GEN_34
             | _GEN_117 & _GEN_34 | _GEN_75 & _GEN_34 | _GEN_120 & _GEN_34 | _GEN_78
             & _GEN_34 | _GEN_122 & _GEN_34 | _GEN_80 & _GEN_34 | _GEN_124 & _GEN_34
             | _GEN_82 & _GEN_34 | _GEN_126 & _GEN_34 | _GEN_84 & _GEN_34 | _GEN_128
             & _GEN_34 | _GEN_86 & _GEN_34 | _GEN_130 & _GEN_34 | _GEN_88 & _GEN_34
             | _GEN_132 & _GEN_34 | _GEN_90 & _GEN_34 | _GEN_134 & _GEN_34 | _GEN_92
             & _GEN_34 | _GEN_136 & _GEN_34)
            ? 4'h8
            : io_rx_symb_vector_valid
              & (_GEN_37 & _GEN_19 & _GEN_24 & _GEN_191 | _GEN_40
                 & (&io_rx_symb_vector_bits_2) & (&io_rx_symb_vector_bits_3) | _GEN_192
                 & _GEN_39 & (&io_rx_symb_vector_bits_3) | _GEN_192
                 & (&io_rx_symb_vector_bits_2) & _GEN_191)
              & (_GEN_156 & _GEN_34 | _GEN_35 & (&rx_symb_vector_prev_2)
                 & (&rx_symb_vector_prev_3) | _GEN_180 & _GEN_33
                 & (&rx_symb_vector_prev_3) | _GEN_190 & _GEN_34)
                ? 4'h9
                : {3'h3,
                   io_rx_symb_vector_valid
                     & (_GEN_10 & _GEN_38 & _GEN_39 & _GEN_13
                        | io_rx_symb_vector_bits_0 == 3'h1 & _GEN_193 & _GEN_39 & _GEN_191
                        | _GEN_194 & io_rx_symb_vector_bits_2 == 3'h1 & _GEN_191
                        | _GEN_194 & _GEN_39 & io_rx_symb_vector_bits_3 == 3'h1)}},
         {{1'h0, ~_GEN_42, 2'h0}},
         {io_rx_symb_vector_valid ? 4'h5 : 4'h3},
         {{3'h1, io_rx_symb_vector_valid}},
         {io_rx_symb_vector_valid & _GEN_36 & _GEN_41
            ? 4'h2
            : io_rx_symb_vector_valid & ~_GEN_36 | ~_GEN_41 ? 4'h4 : 4'h1},
         {{3'h0, ~_GEN_30 & io_rx_symb_vector_valid}}};
      state <= _GEN_195[state];
    end
    if (io_rx_symb_vector_valid) begin
      rx_symb_vector_prev_0 <= io_rx_symb_vector_bits_0;
      rx_symb_vector_prev_1 <= io_rx_symb_vector_bits_1;
      rx_symb_vector_prev_2 <= io_rx_symb_vector_bits_2;
      rx_symb_vector_prev_3 <= io_rx_symb_vector_bits_3;
    end
  end // always @(posedge)
  assign io_rx_symb_vector_ready = 1'h1;
  assign io_receive1000BT = ~_GEN & (_GEN_0 | _GEN_1 | _GEN_8 | _GEN_7);
  assign io_rxerror_status = ~_GEN_9 & _GEN_1;
  assign io_rxd =
    _GEN_9
      ? 8'h0
      : _GEN_1
          ? 8'hE
          : _GEN_8
              ? 8'h55
              : _GEN_7 | state == 4'h9 | state == 4'hA | state == 4'hB
                  ? io_from_decoder_symbols
                  : 8'h0;
  assign io_rx_dv = ~(_GEN | _GEN_0 | _GEN_1) & (_GEN_8 | _GEN_7);
  assign io_rx_er = ~_GEN_9 & (_GEN_1 | ~(_GEN_2 | _GEN_3 | _GEN_4) & (_GEN_5 | _GEN_6));
endmodule

